In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
f = '../data/modificado/ENCEVI_CONSUMO_2.parquet'

ENCEVI_CONSUMO = pd.read_parquet(f)
# print(len(viv))
# viv.dropna(inplace=True)
ENCEVI_CONSUMO

,folio,bill_days,munic_name,bill_kwh_estimation,total_niv,super_ter,super_cons,tot_cuart,electri,local_com,uso_aire,est_socio,factor_sem,entidad,tot_integ
0,2,30,Aguascalientes,128.896444,1,3,3,6,1,2,2,3,373,1,4
1,4,30,Aguascalientes,167.110992,1,3,4,6,1,2,2,3,373,1,1
2,5,30,Aguascalientes,207.517844,1,3,4,5,1,2,2,3,373,1,2
3,6,61,Aguascalientes,69.987390,1,4,2,4,1,2,2,3,387,1,6
4,11,30,Aguascalientes,149.416488,2,2,3,3,1,2,2,3,372,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14442,28913,61,Villa Hidalgo,33.543506,1,5,3,2,1,2,2,2,408,32,2
14443,28917,59,Genaro Codina,168.745539,1,9,5,5,1,2,2,2,338,32,5
14444,28927,62,Genaro Codina,77.180962,1,5,3,3,1,2,2,2,338,32,6
14445,28943,60,Tepetongo,41.689786,1,6,2,3,1,2,2,2,382,32,4
14446,28948,30,Tepetongo,245.776231,2,6,6,5,1,2,2,2,382,32,5

In [3]:
mapeo_m2 = {
    1: 30,
    2: 55,
    3: 75,
    4: 100,
    5: 150,
    6: 200,
    7: np.nan,
    9: np.nan
}

# Crear la nueva columna "m2" aplicando el diccionario de mapeo
ENCEVI_CONSUMO['m2'] = ENCEVI_CONSUMO['super_cons'].map(mapeo_m2)
ENCEVI_CONSUMO['kwh_mes'] = (ENCEVI_CONSUMO['bill_kwh_estimation'] / ENCEVI_CONSUMO['bill_days']) * 30
ENCEVI_CONSUMO['kwh_m2_mes'] = ENCEVI_CONSUMO['kwh_mes']/ENCEVI_CONSUMO['m2']
ENCEVI_CONSUMO

,folio,bill_days,munic_name,bill_kwh_estimation,total_niv,super_ter,super_cons,tot_cuart,electri,local_com,uso_aire,est_socio,factor_sem,entidad,tot_integ,m2,kwh_mes,kwh_m2_mes
0,2,30,Aguascalientes,128.896444,1,3,3,6,1,2,2,3,373,1,4,75.0,128.896444,1.718619
1,4,30,Aguascalientes,167.110992,1,3,4,6,1,2,2,3,373,1,1,100.0,167.110992,1.671110
2,5,30,Aguascalientes,207.517844,1,3,4,5,1,2,2,3,373,1,2,100.0,207.517844,2.075178
3,6,61,Aguascalientes,69.987390,1,4,2,4,1,2,2,3,387,1,6,55.0,34.420028,0.625819
4,11,30,Aguascalientes,149.416488,2,2,3,3,1,2,2,3,372,1,5,75.0,149.416488,1.992220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14442,28913,61,Villa Hidalgo,33.543506,1,5,3,2,1,2,2,2,408,32,2,75.0,16.496806,0.219957
14443,28917,59,Genaro Codina,168.745539,1,9,5,5,1,2,2,2,338,32,5,150.0,85.802816,0.572019
14444,28927,62,Genaro Codina,77.180962,1,5,3,3,1,2,2,2,338,32,6,75.0,37.345627,0.497942
14445,28943,60,Tepetongo,41.689786,1,6,2,3,1,2,2,2,382,32,4,55.0,20.844893,0.378998
14446,28948,30,Tepetongo,245.776231,2,6,6,5,1,2,2,2,382,32,5,200.0,245.776231,1.228881

In [ ]:
# Crear un DataFrame temporal
df_temp = ENCEVI_CONSUMO.copy()

# Definir los pesos
pesos_1 = df_temp['factor_sem']
pesos_2 = df_temp['tot_integ'] * df_temp['factor_sem']
pesos_3 = df_temp['kwh_mes'] * df_temp['factor_sem']

# Variable eje x: 'm2'
variable_x = df_temp['m2']

# Definir los bins para los tamaños específicos
tamanos = [30, 55, 75, 100, 150, 200]
# Para que matplotlib trate bien los bins, extendemos los bordes un poco
bins = [15, 42.5, 65, 87.5, 125, 175, 225]  

# Configurar subplots
fig, axs = plt.subplots(3, 1, figsize=(10, 18))

# Histograma 1: Solo factor_sem
axs[0].hist(variable_x, bins=bins, weights=pesos_1, color='skyblue', rwidth=0.8)
axs[0].set_title('Histograma: Solo factor_sem')
axs[0].set_xlabel('m2')
axs[0].set_ylabel('Frecuencia ponderada')
axs[0].set_xticks(tamanos)  # Poner las etiquetas exactas
axs[0].grid(True)

# Histograma 2: tot_integ * factor_sem
axs[1].hist(variable_x, bins=bins, weights=pesos_2, color='lightgreen', rwidth=0.8)
axs[1].set_title('Histograma: tot_integ * factor_sem')
axs[1].set_xlabel('m2')
axs[1].set_ylabel('Frecuencia ponderada')
axs[1].set_xticks(tamanos)
axs[1].grid(True)

# Histograma 3: kwh_mes * factor_sem
axs[2].hist(variable_x, bins=bins, weights=pesos_3, color='salmon', rwidth=0.8)
axs[2].set_title('Histograma: kwh_mes * factor_sem')
axs[2].set_xlabel('m2')
axs[2].set_ylabel('Frecuencia ponderada')
axs[2].set_xticks(tamanos)
axs[2].grid(True)

# Ajustar el espaciado
plt.tight_layout()
plt.show()